#
# Copyright (c) 2023 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
name: CI (MacOS)

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "0 6 * * 1-5"

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  DEBIAN_FRONTEND: noninteractive

jobs:
  check:
    name: macOS
    runs-on:  "macos-latest"
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: echo ${{ github.sha }} > Release2.txt

      - name: Test
        run: cat Release2.txt

      - name: Generate release tag
        id: tag
        run: |
          pkg_ver=v$(cargo pkgid | cut -d "#" -f2)
          echo "::set-output name=release_tag::$pkg_ver"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: true
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: Release2.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
